In [15]:
import numpy as np
dataset = np.random.randint(100,500,(30,5))
print(dataset)

[[451 449 262 470 379]
 [262 309 429 334 139]
 [117 399 451 145 396]
 [347 463 381 432 132]
 [149 171 352 416 457]
 [120 433 229 158 239]
 [282 350 364 183 441]
 [310 171 312 198 231]
 [228 215 449 338 226]
 [466 263 181 238 440]
 [240 180 253 414 129]
 [158 259 274 310 251]
 [111 473 274 458 291]
 [285 350 196 240 382]
 [473 253 126 162 476]
 [257 102 359 124 398]
 [153 366 222 309 195]
 [186 139 419 488 408]
 [496 227 348 345 360]
 [322 228 475 308 483]
 [207 178 430 139 453]
 [482 190 180 245 445]
 [330 255 200 167 214]
 [227 254 103 352 172]
 [301 358 283 119 157]
 [154 469 385 235 257]
 [117 491 408 197 290]
 [209 210 417 242 229]
 [454 116 132 199 279]
 [443 217 108 464 348]]


In [17]:
avg = (np.sum(dataset,axis =0))/30
avg = [round(a,1) for a in avg]
print("Average stock prices :",avg)
maxi = np.max(dataset)
index = np.argwhere(dataset==maxi)
print(f"Highest price recorded: {maxi} at Day {index[0][0]+1}, Company {index[0][1]}")
norm = np.linalg.norm(dataset)
matrix = dataset/norm
print("Normalized Prices : ")
print(matrix)
print("Risky Investments Days:")
for i in range(len(dataset)):
    mask = dataset[i] <200
    if len(dataset[i][mask]) !=0:
        print(f"Day {i+1} : {dataset[i][mask]}")

Average stock prices : [277.9, 284.6, 300.1, 281.0, 309.9]
Highest price recorded: 496 at Day 19, Company 0
Normalized Prices : 
[[0.1176647  0.11714291 0.06835511 0.12262175 0.09888009]
 [0.06835511 0.08061728 0.11192496 0.08713971 0.03626473]
 [0.03052499 0.10409804 0.1176647  0.03783012 0.10331535]
 [0.09053138 0.12079547 0.09940189 0.11270765 0.03443845]
 [0.0388737  0.04461345 0.09183587 0.1085333  0.11923009]
 [0.03130768 0.11296855 0.05974549 0.04122178 0.06235447]
 [0.07357305 0.09131407 0.09496663 0.04774421 0.11505573]
 [0.08087818 0.04461345 0.08139997 0.05165767 0.06026729]
 [0.0594846  0.05609293 0.11714291 0.0881833  0.0589628 ]
 [0.12157816 0.068616   0.04722242 0.06209357 0.11479483]
 [0.06261536 0.04696152 0.06600703 0.1080115  0.03365576]
 [0.04122178 0.06757241 0.07148587 0.08087818 0.06548523]
 [0.02895961 0.12340445 0.07148587 0.11949099 0.07592113]
 [0.07435574 0.09131407 0.05113588 0.06261536 0.09966279]
 [0.12340445 0.06600703 0.03287307 0.04226537 0.12418714]
 

In [29]:
import numpy as np
minerals = np.random.randint(10,99,(6,3))
print(minerals)

[[72 41 23]
 [21 19 71]
 [78 19 87]
 [13 17 40]
 [18 48 64]
 [74 98 95]]


In [33]:
totalM = np.sum(minerals,axis = 0)
print(f"Oxygen:{totalR[0]}, Water: {totalR[1]}, Food: {totalR[2]}")
maxi = np.max(minerals)
index = np.argwhere(minerals==maxi)
match index[0][1]:
    case 1:
        highComMonth = "Water"
    case 0:
        highComMonth = "Oxygen"
    case 2:
        highComMonth = "Food"

print(f"Highest consumption in a month: {highComMonth} ({maxi} tons in {index[0][0]+1})")
stdOfOxygen = np.std(resources[:,0])
stdOfWater = np.std(resources[:,1])
stdOfFood = np.std(resources[:,2])
print(f"Standard Deviation of consumption: Oxygen: {round(stdOfOxygen,1)}, Water: {round(stdOfWater,1)}, Food: {round(stdOfFood,1)}")
print("Transposed matrix:")
print(minerals.T)

Oxygen:276, Water: 242, Food: 380
Highest consumption in a month: Water (98 tons in 6)
Standard Deviation of consumption: Oxygen: 24.2, Water: 20.0, Food: 31.2
Transposed matrix:
[[72 21 78 13 18 74]
 [41 19 19 17 48 98]
 [23 71 87 40 64 95]]


In [49]:
import numpy as np
info = np.random.randint(10,50,(5,10))
print(info)

[[44 29 26 41 18 18 43 22 24 49]
 [46 21 15 47 33 16 38 18 30 11]
 [46 45 33 37 37 27 37 17 13 46]
 [29 49 17 23 29 36 20 34 33 25]
 [28 11 16 40 18 49 28 29 25 11]]


In [55]:
avg = (np.sum(info,axis =1))/10
for a in avg:
    round(a,1)
print("Average points per game:")
print(avg)





Average points per game:
[31.4 27.5 33.8 29.5 25.5]
